name: ubuntu-x86_64-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: mu578/mu0
        path: mu0
    - uses: actions/checkout@v3
      with:
        repository: mu578/mu8
        path: mu8
    - uses: actions/checkout@v3
      with:
        path: mu9
    - name: Run distcheck
      run: cd mu9/mk && make -f mu9.mk distcheck

# EOF